version: '3'

networks:
  app-tier:
    driver: bridge
services:
  postgres:
    image: postgres:14.9-alipine3.18
    restart: always
    networks:
      - app-tier
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hw-11   
      - POSTGRES_PASSWORD=postgres
      - PORT=5439
    ports:
      -"5439-5439"
    app:
      restart: on-failure
      build:
      networks:
        -app-tier
      depends-on:
        -postgres
      ports:
        -"8080-8080"
      environment:
          -NODE_ENV=docker
          -PORT=8080

